import {states} from '@/lib/states';
import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {isAdmin} from '@/lib/access';
import {catalogue,database,approvedReviews} from '@/lib/database';
import {matches,money,sizes,type Product} from '@/lib/products';
import {env} from 'cloudflare:workers';
export const dynamic='force-dynamic';
type Context={params:Promise<{action:string}>};
const json=(data:unknown,status=200)=>NextResponse.json(data,{status});
export async function GET(request:NextRequest,{params}:Context){const {action}=await params;try{
if(action==='products')return json({products:await catalogue()});
if(action==='reviews')return json({reviews:await approvedReviews(request.nextUrl.searchParams.get('product')||undefined)});
if(action==='chat')return json({mode:(env as typeof env&{OPENAI_API_KEY?:string}).OPENAI_API_KEY?'ai':'guide'});
const user=await getChatGPTUser();if(!user)return json({error:'Sign in to continue.'},401);
if(action==='saved'){await catalogue();return json({products:(await database().prepare('SELECT p.* FROM products p JOIN saved s ON s.product_id=p.id WHERE s.user_id=? AND p.active=1').bind(user.userId).all<Product>()).results})}
if(action==='orders')return json({orders:(await database().prepare('SELECT id,total,status,created_at FROM orders WHERE user_id=? ORDER BY created_at DESC').bind(user.userId).all()).results});
if(action==='admin'){if(!await isAdmin())return json({error:'Owner access required.'},403);return json({products:await catalogue(true),orders:(await database().prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 100').all()).results,reviews:(await database().prepare('SELECT * FROM reviews ORDER BY created_at DESC LIMIT 100').all()).results})}
return json({error:'Not found.'},404);
}catch{return json({error:'This part of the store is temporarily unavailable. Try again.'},503)}}
export async function POST(request:NextRequest,{params}:Context){const {action}=await params;let body:Record<string,unknown>;try{body=await request.json()}catch{return json({error:'Check your request and try again.'},400)}try{
if(action==='chat'){const message=String(body.message||'').trim();if(!message||message.length>500)return json({error:'Enter a question under 500 characters.'},400);const products=await catalogue();const choices=matches(products,message).filter(p=>p.stock>0).slice(0,3);let reply=/size|measurement|fit/.test(message.toLowerCase())?'Compare your bust and waist with our size guide. The Fashion Lab offers a basic estimate; it is not a guaranteed fit.':/deliver|ship|return/.test(message.toLowerCase())?'Delivery is ₦3,500 within Lagos and ₦5,500 to other Nigerian states. Your order is a request; final availability and delivery timing are confirmed before payment.':/order|pay/.test(message.toLowerCase())?'Choose a size, add your piece to the bag and send an order request at checkout. No payment is taken on this website.':!choices.length?'No available pieces match that colour, occasion or budget. Try another search or clear your filters in the shop.':`Start with ${choices.map(p=>`${p.name} (${money(p.price)})`).join(' or ')}. Tell me your occasion, colour or budget to narrow the choice.`;let mode='guide';const key=(env as typeof env&{OPENAI_API_KEY?:string}).OPENAI_API_KEY;if(key){try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-4.1-mini',store:false,max_output_tokens:220,instructions:'You are Verola, a concise Nigerian fashion shopping assistant. Use only this catalogue and facts. Do not invent materials, policies, stock or discounts. Orders are requests, no payment is taken. Delivery Lagos NGN3500, other states NGN5500. Size estimate is basic. Catalogue: '+JSON.stringify(products),input:message}),signal:AbortSignal.timeout(12000)});if(response.ok){const data=await response.json() as {output?:{content?:{type:string;text?:string}[]}[]};const answer=data.output?.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text||'').join(' ');if(answer){reply=answer;mode='ai'}}}catch{}}return json({reply,products:choices,mode})}
if(action==='order'){const email=String(body.email||'').trim().toLowerCase();const name=String(body.name||'').trim();const phone=String(body.phone||'').trim();const address=String(body.address||'').trim();const city=String(body.city||'').trim();const state=String(body.state||'').trim();type Item={id:string;size:string;quantity:number};const items=body.items as Item[];if(email.length>180||!states.includes(state)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||[name,phone,address,city,state].some(v=>v.length<2||v.length>180)||!Array.isArray(items)||!items.length||items.length>20||items.some(i=>!i||typeof i.id!=='string'||!sizes.includes(i.size)||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>10)||new Set(items.map(i=>i.id+':'+i.size)).size!==items.length)return json({error:'Check your contact details, address and selected sizes.'},400);const products=await catalogue();const counts=new Map<string,number>();for(const i of items)counts.set(i.id,(counts.get(i.id)||0)+i.quantity);if(items.some(i=>!products.some(p=>p.id===i.id&&p.stock>=(counts.get(i.id)||0))))return json({error:'A piece is unavailable in that quantity. Update your bag.'},409);const subtotal=items.reduce((sum,i)=>sum+products.find(p=>p.id===i.id)!.price*i.quantity,0);const delivery=state==='Lagos'?3500:5500;const id='VM-'+crypto.randomUUID().slice(0,8).toUpperCase();const user=await getChatGPTUser();await database().batch([database().prepare('INSERT INTO orders (id,user_id,email,name,phone,address,city,state,subtotal,delivery,total,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,user?.userId||null,email,name,phone,address,city,state,subtotal,delivery,subtotal+delivery,'Requested',new Date().toISOString()),...items.map(i=>{const p=products.find(p=>p.id===i.id)!;return database().prepare('INSERT INTO order_items (id,order_id,product_id,name,image,size,quantity,price) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,p.id,p.name,p.image,i.size,i.quantity,p.price)})]);return json({id,total:subtotal+delivery},201)}
if(action==='review'){const email=String(body.email||'').trim().toLowerCase();const order=String(body.order||'').trim().toUpperCase();const product=String(body.product||'');const name=String(body.name||'').trim();const text=String(body.text||'').trim();const rating=Number(body.rating);if(!name||name.length>80||text.length<10||text.length>1200||!Number.isInteger(rating)||rating<1||rating>5)return json({error:'Add your name, a rating and a review between 10 and 1,200 characters.'},400);const verified=await database().prepare('SELECT o.id FROM orders o JOIN order_items i ON i.order_id=o.id WHERE o.id=? AND o.email=? AND i.product_id=?').bind(order,email,product).first();if(!verified)return json({error:'The order reference and email do not match this piece.'},400);await database().prepare('INSERT INTO reviews (id,product_id,name,email,order_id,rating,body,status,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),product,name,email,order,rating,text,'Pending',new Date().toISOString()).run();return json({message:'Thank you. Your review has been sent for approval.'},201)}
const user=await getChatGPTUser();if(!user)return json({error:'Sign in to save pieces.'},401);
if(action==='saved'){const id=String(body.id||'');const products=await catalogue();if(!products.some(p=>p.id===id))return json({error:'Piece unavailable.'},404);if(body.remove)await database().prepare('DELETE FROM saved WHERE user_id=? AND product_id=?').bind(user.userId,id).run();else await database().prepare('INSERT OR IGNORE INTO saved (user_id,product_id) VALUES (?,?)').bind(user.userId,id).run();return json({saved:!body.remove})}
if(action==='admin'){if(!await isAdmin())return json({error:'Owner access required.'},403);if(body.kind==='product'){const price=Number(body.price),stock=Number(body.stock);if(!Number.isInteger(price)||price<1||price>10000000||!Number.isInteger(stock)||stock<0||stock>10000)return json({error:'Enter a valid price and stock count.'},400);await database().prepare('UPDATE products SET price=?,stock=?,active=? WHERE id=?').bind(price,stock,body.active?1:0,String(body.id)).run()}else if(body.kind==='order'){const states=['Requested','Processing','Dispatched','Completed','Cancelled'];if(!states.includes(String(body.status)))return json({error:'Invalid order status.'},400);await database().prepare('UPDATE orders SET status=? WHERE id=?').bind(String(body.status),String(body.id)).run()}else if(body.kind==='review'){if(!['Approved','Rejected'].includes(String(body.status)))return json({error:'Invalid review status.'},400);await database().prepare('UPDATE reviews SET status=? WHERE id=?').bind(String(body.status),String(body.id)).run()}else return json({error:'Unknown action.'},400);return json({ok:true})}
return json({error:'Not found.'},404)
}catch{return json({error:'We could not complete that request. Please try again.'},503)}}
