export type Product={id:string;slug:string;name:string;category:string;color:string;price:number;stock:number;active:number;image:string;description:string};
export const sizes=['XS','S','M','L','XL'];
export const money=(value:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(value);
export const collection:Product[]=[
{id:'vm-dress',slug:'the-wine-drape',name:'The Wine Drape',category:'Dresses',color:'Wine',price:88000,stock:12,active:1,image:'/images/wine-dress.webp',description:'An off-shoulder neckline and a sculptural drape. A considered silhouette for celebrations, dinners and evenings that deserve a little more.'},
{id:'vm-set',slug:'the-ivory-pair',name:'The Ivory Pair',category:'Sets',color:'Ivory',price:76000,stock:10,active:1,image:'/images/ivory-set.webp',description:'An ivory waistcoat and wide-leg trousers. Wear the complete look, or make each piece part of your everyday wardrobe.'},
{id:'vm-top',slug:'the-indigo-form',name:'The Indigo Form',category:'Tops',color:'Indigo',price:42000,stock:15,active:1,image:'/images/indigo-top.webp',description:'A sculptural blouse in deep indigo, with long sleeves and a distinctive shape. Pair with simple trousers and let the silhouette lead.'}
];
export function matches(products:Product[],query:string){const q=query.toLowerCase().trim();if(!q)return products;const budget=q.match(/(?:under|below|budget)\s*(?:₦|ngn|n)?\s*([\d,]+)\s*(k)?/);const cap=budget?Number(budget[1].replaceAll(',',''))*(budget[2]?1000:1):Infinity;const color=products.find(p=>q.includes(p.color.toLowerCase()))?.color;const category=/dress|wedding|party|dinner|evening/.test(q)?'Dresses':/set|office|work|tailored/.test(q)?'Sets':/top|blouse|shirt/.test(q)?'Tops':null;const intent=budget||color||category;return products.filter(p=>p.price<=cap&&(!color||p.color===color)&&(!category||p.category===category)&&(intent||`${p.name} ${p.color} ${p.category}`.toLowerCase().includes(q)))}
