'use client';
import {createContext,useContext,useEffect,useState,useCallback} from 'react';
import type {Product} from '@/lib/products';
export type BagItem={product:Product;size:string;quantity:number};
export function sizeCapacity(items:BagItem[],product:Product,size:string){const otherSizes=items.filter(i=>i.product.id===product.id&&i.size!==size).reduce((n,i)=>n+i.quantity,0);return Math.max(0,Math.min(10,product.stock-otherSizes))}
export function bagLimit(items:BagItem[],product:Product,size:string){return (items.find(i=>i.product.id===product.id&&i.size===size)?.quantity||0)>=sizeCapacity(items,product,size)}
const BagContext=createContext<{items:BagItem[];ready:boolean;add:(p:Product,size:string,quantity?:number)=>void;change:(id:string,size:string,quantity:number)=>void;clear:()=>void}>({items:[],ready:false,add:()=>{},change:()=>{},clear:()=>{}});
export function BagProvider({children}:{children:React.ReactNode}){const [items,setItems]=useState<BagItem[]>([]);const [ready,setReady]=useState(false);useEffect(()=>{const frame=requestAnimationFrame(()=>{try{const data=JSON.parse(localStorage.getItem('velmora-atelier-bag')||'[]');if(Array.isArray(data))setItems(data.filter(i=>i?.product?.id&&['XS','S','M','L','XL'].includes(i.size)&&Number.isInteger(i.quantity)&&i.quantity>0&&i.quantity<=10))}catch{}setReady(true)});return()=>cancelAnimationFrame(frame)},[]);useEffect(()=>{if(ready)try{localStorage.setItem('velmora-atelier-bag',JSON.stringify(items))}catch{}},[items,ready]);const add=useCallback((product:Product,size:string,quantity=1)=>{if(!product.stock)return;setItems(current=>{const same=current.find(i=>i.product.id===product.id&&i.size===size);const capacity=sizeCapacity(current,product,size);if(!capacity)return current;return same?current.map(i=>i===same?{...i,quantity:Math.min(i.quantity+quantity,capacity)}:i):[...current,{product,size,quantity:Math.min(quantity,capacity)}]})},[]);return <BagContext.Provider value={{items,ready,add,change:(id,size,quantity)=>setItems(current=>quantity<1?current.filter(i=>i.product.id!==id||i.size!==size):current.map(i=>i.product.id===id&&i.size===size?{...i,quantity:Math.min(quantity,sizeCapacity(current,i.product,size))}:i)),clear:()=>setItems([])}}>{children}</BagContext.Provider>}
export const useBag=()=>useContext(BagContext);
