/* Native navigation keeps these storefront destinations usable during client transitions. */
/* eslint-disable @next/next/no-html-link-for-pages */
'use client';
import {usePathname} from 'next/navigation';
import {Menu,Search,ShoppingBag,UserRound,ChevronDown,Home,Heart,Shirt} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuGroup,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {useBag} from './bag-context';
const explore=[['Fashion Lab','/fashion-lab'],['My closet','/closet'],['Style gallery','/gallery'],['Journal','/journal'],['Runway','/runway'],['Our story','/about']];
export function Navigation(){const {items,ready}=useBag();const path=usePathname();const count=items.reduce((n,i)=>n+i.quantity,0);return <><a className="skip" href="#content">Skip to content</a><header className="masthead"><Sheet><SheetTrigger className="mobile-menu icon-button" aria-label="Open navigation"><Menu size={22}/></SheetTrigger><SheetContent side="left" className="navigation-sheet"><SheetHeader><SheetTitle>VELMORA</SheetTitle><SheetDescription>Shopping and styling</SheetDescription></SheetHeader><nav aria-label="Mobile menu">{[['The collection','/shop'],['Search','/search'],['Dresses','/shop?category=Dresses'],['Sets','/shop?category=Sets'],['Tops','/shop?category=Tops'],...explore,['Saved pieces','/saved'],['My account','/account']].map(([name,url])=><SheetClose asChild key={name}><a href={url}>{name}</a></SheetClose>)}</nav></SheetContent></Sheet><nav className="nav-left" aria-label="Shop"><a href="/shop" aria-current={path==='/shop'?'page':undefined}>Shop</a><a href="/shop?category=Dresses">Dresses</a><a href="/shop?category=Sets">Sets</a><a href="/shop?category=Tops">Tops</a></nav><a className="brand" href="/" aria-label="Velmora home">VELMORA</a><div className="nav-right"><DropdownMenu><DropdownMenuTrigger className="explore-button">Explore <ChevronDown size={13}/></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuGroup>{explore.map(([name,url])=><DropdownMenuItem asChild key={url}><a href={url}>{name}</a></DropdownMenuItem>)}</DropdownMenuGroup></DropdownMenuContent></DropdownMenu><a className="icon-button" href="/search" aria-label="Search"><Search size={19}/></a><a className="icon-button account-icon" href="/account" aria-label="Your account"><UserRound size={19}/></a><a className="icon-button" href="/bag" aria-label={ready?`Bag with ${count} ${count===1?'item':'items'}`:'Your bag'}><ShoppingBag size={19}/>{ready&&<span>{count}</span>}</a></div></header>{!path.startsWith('/product/')&&<nav className="mobile-bottom" aria-label="Quick navigation">{[[Home,'Home','/'],[Search,'Shop','/shop'],[Shirt,'Style','/fashion-lab'],[Heart,'Saved','/saved'],[ShoppingBag,ready?`Bag (${count})`:'Bag','/bag']].map(([Icon,name,url])=>{const I=Icon as typeof Home;return <a href={url as string} key={url as string} aria-current={path===url||(url==='/shop'&&path==='/search')?'page':undefined}><I size={20}/><span>{name as string}</span></a>})}</nav>}</>}
export function Footer(){return <footer className="footer"><div className="footer-brand"><a className="brand" href="/">VELMORA</a><p>Contemporary Nigerian womenswear.<br/>A wardrobe with a point of view.</p><a className="text-link" href="/about">Our story</a></div><div><h2>Discover</h2><a href="/shop">The collection</a><a href="/fashion-lab">Fashion Lab</a><a href="/journal">Journal</a><a href="/runway">Lookbook</a></div><div><h2>Your wardrobe</h2><a href="/account">My account</a><a href="/saved">Saved pieces</a><a href="/closet">My closet</a><a href="/gallery">Style gallery</a></div><div><h2>Here to help</h2><a href="/size-guide">Size guide</a><a href="/delivery">Delivery & returns</a><a href="/showcase">Portfolio showcase</a></div><div className="footer-bottom"><span>© 2026 VELMORA</span><span>Made for your point of view.</span><span>Nigeria · NGN ₦</span></div></footer>}
