 'use client';
import {useState} from 'react';
import {ShoppingBag,Check,ArrowUpRight} from 'lucide-react';
import {type Product,money,sizes} from '@/lib/products';
import {useBag,bagLimit} from './bag-context';
import {SavePiece} from './save-piece';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
export function Piece({product,initialSaved=false,onRemoved}:{product:Product;initialSaved?:boolean;onRemoved?:()=>void}){const [size,setSize]=useState(''),[added,setAdded]=useState(false);const {add,ready,items}=useBag();const limit=bagLimit(items,product,size);return <article className="piece"><div className="piece-photo"><a href={`/product/${product.slug}`}><img src={product.image} alt={`${product.name} in ${product.color}`} width={1024} height={1536} loading="lazy"/></a><SavePiece product={product} initialSaved={initialSaved} onRemoved={onRemoved}/></div><div className="piece-information"><div><a className="piece-name" href={`/product/${product.slug}`}>{product.name}</a><p className="piece-category">{product.category} · {product.color}</p></div><span className="piece-price">{money(product.price)}</span></div><Sheet><SheetTrigger className="piece-choose" disabled={!product.stock}><ShoppingBag size={15}/>{product.stock?'Choose size':'Sold out'}<ArrowUpRight size={15}/></SheetTrigger><SheetContent className="quick-add-sheet"><SheetHeader><SheetTitle>Choose your size</SheetTitle><SheetDescription>A little closer to your next look.</SheetDescription></SheetHeader><div className="quick-add-body"><div className="quick-add-product"><img src={product.image} alt={product.name}/><div><h2>{product.name}</h2><p>{product.color}</p><strong>{money(product.price)}</strong></div></div><div className="size-top"><span>Select size</span><a className="text-link" href="/size-guide">Size guide</a></div><RadioGroup className="size-options" value={size} onValueChange={s=>{setSize(s);setAdded(false)}} aria-label={`Size for ${product.name}`}>{sizes.map(s=><label key={s} className={size===s?'selected':''}><RadioGroupItem value={s} className="sr-only"/>{s}</label>)}</RadioGroup><button className="button full" disabled={!ready||!size||limit} onClick={()=>{add(product,size);setAdded(true)}}>{limit?'Maximum quantity in bag':'Add to bag'}</button><p className="feedback" role="status">{added&&<><Check size={16}/>Added in {size}. <a className="text-link" href="/bag">View bag</a></>}</p><a className="text-link" href={`/product/${product.slug}`}>View full details <ArrowUpRight size={15}/></a></div></SheetContent></Sheet></article>}
